import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  output: "standalone",

  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "cdn.sanity.io",
      },
    ],
  },

  async redirects() {
    return [
      // ── Existing service page redirects (Hebrew → English) ──────────
      { source: '/services/החזר-מס-שבח', destination: '/services/real-estate-tax', permanent: true },
      { source: '/services/ניהול-דיונים-מול-רשויות-המס', destination: '/services/tax-representation', permanent: true },
      { source: '/services/החזרי-מס', destination: '/services/tax-refunds', permanent: true },
      { source: '/services/מענקים', destination: '/services/grants', permanent: true },

      // ── Structural pages ────────────────────────────────────────────
      { source: '/אודות', destination: '/about', permanent: true },
      { source: '/צור-קשר', destination: '/contact', permanent: true },

      // ── P1 articles: old WP Hebrew URL → new /knowledge/[slug] ─────
      { source: '/בעלי-הכנס-מעבודה-בחול', destination: '/knowledge/income-from-work-abroad', permanent: true },
      { source: '/דירת-מגורים-מזכה', destination: '/knowledge/qualifying-residential-apartment', permanent: true },
      { source: '/הוצאות-נלוות', destination: '/knowledge/ancillary-expenses', permanent: true },
      { source: '/הוצאות-נסיעות-לחול-מוכרות-למס-הכנסה', destination: '/knowledge/deductible-travel-expenses-abroad', permanent: true },
      { source: '/היערכות-חברות-לתום-שנת-מס-2016', destination: '/knowledge/year-end-prep-companies-2016', permanent: true },
      { source: '/הערכות-חברה-לתום-שנת-2018', destination: '/knowledge/year-end-prep-companies-2019', permanent: true },
      { source: '/הקשר-בין-סעיף-174-לפקודת-מס-הכנסה-להודעת-ז', destination: '/knowledge/section-17-4-credit-note-connection', permanent: true },
      { source: '/זכאות-לשיעור-מס-מופחת-אזרחים-מעל-גיל-60', destination: '/knowledge/reduced-tax-rate-over-60', permanent: true },
      { source: '/חוזר-מקצועי-שינויים-בשכר-החל-מיום-1-בי', destination: '/knowledge/salary-changes-january-2017', permanent: true },
      { source: '/חישוב-גידול-קיטון-בהון-מקורות-ושימוש', destination: '/knowledge/wealth-increase-decrease-sources-uses', permanent: true },
      { source: '/כללים-להוצאת-הודעת-זיכוי-חשבונית-זיכו', destination: '/knowledge/credit-note-rules', permanent: true },
      { source: '/מענק-עבודה', destination: '/knowledge/work-grant-negative-income-tax', permanent: true },
      { source: '/סוגי-תשלומים-שהעברתם-לתושב-חוץ-פטורה-מ', destination: '/knowledge/payments-to-foreign-residents-withholding-exempt', permanent: true },
      { source: '/פטור-חד-פעמי-ממס-שבח-על-2-דירות', destination: '/knowledge/one-time-betterment-tax-exemption-two-apartments', permanent: true },
      { source: '/פטור-ממס-שבח', destination: '/knowledge/betterment-tax-exemption', permanent: true },
      { source: '/פטור-ממשיכת-כספי-תגמולים-החייבים-ב-35-מס', destination: '/knowledge/severance-fund-withdrawal-35-percent-exemption', permanent: true },
      { source: '/פריסת-מס-שבח', destination: '/knowledge/betterment-tax-spreading', permanent: true },
      { source: '/ריכוז-טבלת-שיעורי-המס-החלים-על-הכנסות-ו', destination: '/knowledge/tax-rate-table-summary', permanent: true },
      { source: '/שאלות-ותשובות-בנושא-דברים-שחובה-בחשבו', destination: '/knowledge/invoice-requirements-faq', permanent: true },
      { source: '/תיקון-190', destination: '/knowledge/amendment-190', permanent: true },
      { source: '/תשלום-מס-שבח', destination: '/knowledge/betterment-tax-payment', permanent: true },

      // ── P2 bumped articles (published) ──────────────────────────────
      { source: '/הקפאת-עדכוני-מס-ומס-יסף', destination: '/knowledge/tax-bracket-freeze-surcharge-2025', permanent: true },
      { source: '/חברת-מעטים', destination: '/knowledge/closely-held-company', permanent: true },
      { source: '/עדכון-חקיקה-מעמ-18', destination: '/knowledge/vat-18-percent-update-2025', permanent: true },
      { source: '/רווחים-כלואים', destination: '/knowledge/trapped-profits', permanent: true },

      // ── Batch 2 articles: WP → /knowledge/[slug] ──────────────────────
      { source: '/מעמ-בגין-שכט-לשירותי-ייעוץ-לחברה-בחול', destination: '/knowledge/vat-consulting-fees-foreign-company', permanent: true },
      { source: '/האם-יש-לגבות-17-מעמ-לחברה-מחוץ-לאילת-בגין', destination: '/knowledge/vat-eilat-interest-loan', permanent: true },
      { source: '/מעמ-0-לנותני-שירותים-לאילת', destination: '/knowledge/vat-zero-rate-tourist-services', permanent: true },
      { source: '/מעמ-על-תווי-שי', destination: '/knowledge/vat-on-gift-vouchers', permanent: true },
      { source: '/תשלום-מעמ-עבור-שטח-בדירה-המשמש-לעסק', destination: '/knowledge/vat-home-office-space', permanent: true },
      { source: '/הגבלות-חדשות-בתחום-הנדלן-החל-מה-1-לינוא', destination: '/knowledge/real-estate-restrictions-2019', permanent: true },
      { source: '/woman-pregnent', destination: '/knowledge/women-employment-maternity-leave', permanent: true },
      { source: '/האם-בעל-עסק-חייב-להפריש-לקופת-פנסיה-או-י', destination: '/knowledge/employer-pension-vs-provident-fund', permanent: true },
      { source: '/חוק-דמי-מחלה-לעובד', destination: '/knowledge/employee-sick-pay-law', permanent: true },
      { source: '/פיצויים-לעובד-שהתפטר-עקב-העתקת-מקום-מג', destination: '/knowledge/resignation-relocation-severance', permanent: true },
      { source: '/זכאות-לפיצויים-ודמי-אבטלה-לעובדת-שילד', destination: '/knowledge/maternity-severance-unemployment', permanent: true },
      { source: '/6068-2', destination: '/knowledge/annual-companies-registrar-fee-2020', permanent: true },
      { source: '/האם-בעל-עסק-שמעברים-לו-תשלום-בהעברה-בנק', destination: '/knowledge/bank-transfer-receipt-requirement', permanent: true },
      { source: '/שפת-חשבונית-לבעל-עסק-הנותן-שירות-מוכר-מ', destination: '/knowledge/invoice-language-foreign-clients', permanent: true },
      { source: '/עסק-חדש-ברכותינו-דגשים-חשובים-להתחלה', destination: '/knowledge/opening-new-business', permanent: true },
      { source: '/הפחתה-ביטוח-לאומי-לעצמאים', destination: '/knowledge/national-insurance-self-employed', permanent: true },
      { source: '/האם-ניתן-לדרוש-את-יתרת-ההשקעה-על-נכס-כהו', destination: '/knowledge/remaining-asset-investment-current-expense', permanent: true },
      { source: '/הוראות-ניהול-ספרים-מס-הכנסה', destination: '/knowledge/bookkeeping-requirements-income-tax', permanent: true },
      { source: '/הורחב-מתווה-הפיצויים-לתושבי-הדרום', destination: '/knowledge/southern-residents-compensation-expansion', permanent: true },
      { source: '/עדכון-לבעלי-עסקים-באיזור-עוטף-עזה-והדר', destination: '/knowledge/gaza-envelope-business-update', permanent: true },

      // ── P1 articles not republished → knowledge hub ─────────────────
      { source: '/בלוק-בדף-הבית', destination: '/knowledge', permanent: true },
      { source: '/איחוד-עוסקים-דוחות-ודיווחים-לרשויות', destination: '/knowledge', permanent: true },

      // ── P2 articles not republished → knowledge hub ─────────────────
      { source: '/היערכות-עוסקים-פטורים-לתום-שנת-המס-2016', destination: '/knowledge', permanent: true },
      { source: '/זיכוי-בגין-ילדים-קטנים', destination: '/knowledge', permanent: true },
      { source: '/זיכוי-בגין-סיום-תואר-אקדמי', destination: '/knowledge', permanent: true },
      { source: '/זיכוי-בעד-ילדים-נטולי-יכולת', destination: '/knowledge', permanent: true },
      { source: '/זיכוי-הורה-גרוש-מזונות-2', destination: '/knowledge', permanent: true },
      { source: '/זיכוי-הנצחת-בן-משפחה-חיל-שוטר-פעולות-אי', destination: '/knowledge', permanent: true },
      { source: '/זיכוי-ליחיד-במשפחה-חד-הורית', destination: '/knowledge', permanent: true },
      { source: '/זיכוי-לתושבים-ביישובים-מזכים', destination: '/knowledge', permanent: true },
      { source: '/זיכוי-ממס-הכנסה-לעולה-חדש', destination: '/knowledge', permanent: true },
      { source: '/זיכוי-מס-בגין-תרומה', destination: '/knowledge', permanent: true },
      { source: '/מדרגות-מס-2006-2017', destination: '/knowledge', permanent: true },
      { source: '/מספר-עובדות-מדרגות-מס', destination: '/knowledge', permanent: true },
      { source: '/סעיף-45א-נקודות-זיכוי-בגין-ילד-נטול-יכול', destination: '/knowledge', permanent: true },
      { source: '/ריבית-סעיף-3ט-לפקודה', destination: '/knowledge', permanent: true },

      // ── P3 articles → knowledge hub ─────────────────────────────────
      { source: '/אאא', destination: '/knowledge', permanent: true },
      { source: '/אופן-העברת-מידע-למנהל-מס-ערך-מוסף-האיזו', destination: '/knowledge', permanent: true },
      { source: '/אופן-חישוב-שכירות-הכנסה-מדירת-מגורים', destination: '/knowledge', permanent: true },
      { source: '/בדיקת-זכאות-לסטודנטים', destination: '/knowledge', permanent: true },
      { source: '/במסגרת-חוק-צמצום-שימוש-מזומן-דין-עסקאו', destination: '/knowledge', permanent: true },
      { source: '/גיוס-מנהלת-חשבונות', destination: '/knowledge', permanent: true },
      { source: '/דרישת-הצהרת-הון-מתושב-חוץ', destination: '/knowledge', permanent: true },
      { source: '/companytax', destination: '/knowledge/company-capital-gains-tax-spreading', permanent: true },
      { source: '/compensation', destination: '/knowledge/vat-on-contract-compensation', permanent: true },
      { source: '/האם-פיצוי-בגין-הפרת-הסכם-מחוייב-במעמ', destination: '/knowledge', permanent: true },
      { source: '/הגבלות-מקרקעין-2019', destination: '/knowledge', permanent: true },
      { source: '/הודעה-על-דחיית-מועד-הגשת-דיווח-בגין-עמ', destination: '/knowledge', permanent: true },
      { source: '/היבטים-פליליים-בהגשת-הצהרת-הון', destination: '/knowledge', permanent: true },
      { source: '/הסבר-על-מסלול-מקוצר-להוצאה-לפועל-בהתאם', destination: '/knowledge', permanent: true },
      { source: '/הערכות-הגשה-דוחות-שנת-2017', destination: '/knowledge', permanent: true },
      { source: '/הערכות-הגשת-דוחות', destination: '/knowledge', permanent: true },
      { source: '/הפחתת-מס-חברות', destination: '/knowledge', permanent: true },
      { source: '/הפרשה-חשבונאית-באילו-מצבים-ניתן-להכיר', destination: '/knowledge', permanent: true },
      { source: '/תיקון-חוק-הטבות-וייעוץ-מס', destination: '/knowledge', permanent: true },
      { source: '/חוק-חופשה-תוספת-לחוק-יום-בחירה-עובד', destination: '/knowledge', permanent: true },
      { source: '/טיפים-למלצרים-יחוייבו-במעמ', destination: '/knowledge', permanent: true },
      { source: '/check-your-rights', destination: '/knowledge', permanent: true },
      { source: '/כמה-נקודות-שחשוב-להכיר-לגבי-העסקת-נערי', destination: '/knowledge', permanent: true },
      { source: '/מבחנים-להכרה-בחוב-אבוד', destination: '/knowledge', permanent: true },
      { source: '/מחזיקים-בחוב-אבוד-עקב-אי-תשלום-רעיון-נו', destination: '/knowledge', permanent: true },
      { source: '/מעמ-על-רכב-להסעת-נוסעים', destination: '/knowledge', permanent: true },
      { source: '/הפרשה-חשבונאית', destination: '/knowledge/accounting-provision-tax-recognition', permanent: true },
      { source: '/מקרים-בהם-יש-לדווח-למעמ-דיווח-מפורט', destination: '/knowledge', permanent: true },
      { source: '/ניהול-תזרים-מזומנים', destination: '/knowledge', permanent: true },
      { source: '/נכסים-והתחייבויות-בהצהרת-הון', destination: '/knowledge', permanent: true },
      { source: '/birthandtax', destination: '/knowledge', permanent: true },
      { source: '/רווחים-כלואים-וחברת-מעטים', destination: '/knowledge', permanent: true },
      { source: '/עקרון-התא-המשפחתי', destination: '/knowledge', permanent: true },
      { source: '/פחת-על-אתר-אינטרנט', destination: '/knowledge', permanent: true },
      { source: '/פינת-ההשראה-אין-גיל-צעיר-מדי-להגשים-חלו', destination: '/knowledge', permanent: true },
      { source: '/פריסת-מס-פיצויים-חייבים-במס', destination: '/knowledge', permanent: true },
      { source: '/קיבוע-זכויות-פנסיה', destination: '/knowledge', permanent: true },
      { source: '/קיזוז-הפסדים-מס-שבח-2', destination: '/knowledge', permanent: true },
      { source: '/קצבת-נכות-פטורה-ממס', destination: '/knowledge', permanent: true },
      { source: '/car-tex', destination: '/knowledge', permanent: true },
      { source: '/רעידת-אדמה-בעולם-התיירות-2', destination: '/knowledge', permanent: true },
      { source: '/שימוש-מס-ופטור-לחברה-זרה-שמחזיקה-בחברה', destination: '/knowledge', permanent: true },
      { source: '/שיעור-מס-על-דיבידנד-עפי-סעיף-125ב-לפקודת-מ', destination: '/knowledge', permanent: true },
      { source: '/cash-low', destination: '/knowledge', permanent: true },
      { source: '/תיאום-מס-לא-מסובך-כמו-שזה-נשמע-2', destination: '/knowledge', permanent: true },
      { source: '/תשלום-אגרה-מופחתת-לרשם-החברות-עד-תאריך-2', destination: '/knowledge', permanent: true },
      { source: '/תשלום-מס-במקרה-של-דירת-ירושה-אותה-מחזיק', destination: '/knowledge', permanent: true },

      // ── Skip articles → knowledge hub ───────────────────────────────
      { source: '/change-address', destination: '/knowledge/changing-company-address', permanent: true },
      { source: '/בקשה-לדחיית-נקודת-זיכוי-שנדחתה-בגין-יל', destination: '/knowledge', permanent: true },
      { source: '/change-your-company-name', destination: '/knowledge/changing-company-name', permanent: true },
      { source: '/חישוב-הכנסה-משכירות-תושב-חוץ', destination: '/knowledge', permanent: true },
      { source: '/תושב-ישראל-בעל-חברה-ישראלית-מחזיק-בחבר', destination: '/knowledge', permanent: true },

      // ── Remaining WP posts → knowledge hub (batch 3 — full coverage) ──
      { source: '/avi_bitan', destination: '/about', permanent: true },
      { source: '/ron_bitan', destination: '/about', permanent: true },
      { source: '/shlomo_bitan', destination: '/about', permanent: true },
      { source: '/homer_roe_heshbon', destination: '/knowledge', permanent: true },
      { source: '/purchasetax', destination: '/knowledge', permanent: true },
      { source: '/banking', destination: '/knowledge', permanent: true },
      { source: '/divident', destination: '/knowledge', permanent: true },
      { source: '/pension', destination: '/knowledge', permanent: true },
      { source: '/invoice', destination: '/knowledge', permanent: true },
      { source: '/פטור-ממס-הכנסה-לאנשים-בעלי-מוגבלויות', destination: '/knowledge', permanent: true },
      { source: '/משתמש-ברכב-חברה-לצרכיך-האישיים-האם-נית', destination: '/knowledge', permanent: true },
      { source: '/עובדים-מול-ספקים-ויש-הפרשים-בחשבונית-ה', destination: '/knowledge', permanent: true },
      { source: '/האם-עדיין-צריך-לשלם-מס-על-עסקה-שבוטלה-לא', destination: '/knowledge', permanent: true },
      { source: '/משיכה-מוקדמת-מרכיב-תגמולים-בקופת-גמל-ב', destination: '/knowledge', permanent: true },
      { source: '/זכיתם-בפרס-או-הגרלה-מזל-טוב-כמה-מס-תצטר', destination: '/knowledge', permanent: true },
      { source: '/בעל-עסק-אוהב-סיכונים', destination: '/knowledge', permanent: true },
      { source: '/קבלו-כמה-טיפים-לחיסכון-במס', destination: '/knowledge', permanent: true },
      { source: '/עובדי-הייטק-המחזיקים-אופציות-שימו-לב-ל', destination: '/knowledge', permanent: true },
      { source: '/פינת-ההשראה-לעולם-לא-מאוחר-מדי', destination: '/knowledge', permanent: true },
      { source: '/דחיית-מועד-הגשת-הדוחות-השנתיים', destination: '/knowledge', permanent: true },
      { source: '/פטור-מתשלום-מסים-על-מוצרים-מהדיוטי-פרי', destination: '/knowledge', permanent: true },
      { source: '/דירוג-אשראי-אישי', destination: '/knowledge', permanent: true },
      { source: '/הקניון-הראשון-מחות-לאילת-ללא-מעמ', destination: '/knowledge', permanent: true },
      { source: '/דיווח-נכסים-והתחייבויות-לבן-זוג-בנישו', destination: '/knowledge', permanent: true },
      { source: '/החזר-מעמ-על-רכב-שמשמש-להסעת-נוסעים-בלב', destination: '/knowledge', permanent: true },
      { source: '/דין-עדכון-למס-הכנסה-בדבר-סגירת-העסק', destination: '/knowledge', permanent: true },
      { source: '/האם-העמותה-שאתם-מעוניינים-לתרום-לה-מוכ', destination: '/knowledge', permanent: true },
      { source: '/הטבות-מס-לנשים', destination: '/knowledge', permanent: true },
      { source: '/בדקו-מה-הסכום-המירבי-המותר-לשימוש-לתשל', destination: '/knowledge', permanent: true },
      { source: '/סימולטור-שימושי-בהמשך-לחוק-צמצום-השימ', destination: '/knowledge', permanent: true },
      { source: '/מיסים-על-מטבעות-וירטואליים', destination: '/knowledge', permanent: true },
      { source: '/תזכורת-להורים-עובדיםתיקון-לחוק-מס-הכנ', destination: '/knowledge', permanent: true },
      { source: '/תזכורת-מרשות-המסים-למשתחררים-משירות-צ', destination: '/knowledge', permanent: true },
      { source: '/לבעלי-עסקים-באיזור-עוטף-עזה', destination: '/knowledge', permanent: true },
      { source: '/תכנון-ופיתוח-העסק', destination: '/knowledge', permanent: true },
      { source: '/הוצאות-מוכרות-לרכב-המיועד-להסעת-תיירי', destination: '/knowledge', permanent: true },
      { source: '/כיצד-יש-לפעול-בעת-השמדת-מלאי-לפי-הוראות', destination: '/knowledge', permanent: true },
      { source: '/הערכות-חברות-לתום-שנת-2018', destination: '/knowledge', permanent: true },
      { source: '/תקרת-עוסק-פטור-2018', destination: '/knowledge', permanent: true },
      { source: '/הערכות-עצמאים-לתום-שנת-מס-2018', destination: '/knowledge', permanent: true },
      { source: '/המערכת-שעשויה-להוזיל-לנו-את-הריביות-על', destination: '/knowledge', permanent: true },
      { source: '/האם-סיוע-כלכלי-מחוייב-במעמ', destination: '/knowledge', permanent: true },
      { source: '/האם-מכירת-ציוד-לעסק-נכנס-כחלק-מתקרת-עוס', destination: '/knowledge', permanent: true },
      { source: '/האם-אפשר-להוציא-חשבוניות-קבלות-במסמך-word', destination: '/knowledge', permanent: true },
      { source: '/האם-כוס-קפה-עם-לקוח-בבית-קפה-נחשבת-הוצא-2', destination: '/knowledge', permanent: true },
      { source: '/מה-אחוז-ניכוי-מעמ-על-רכישת-סמארטפון', destination: '/knowledge', permanent: true },
      { source: '/משיכת-כספים-מקופת-פנסיה-ללא-אישור-מעסי', destination: '/knowledge', permanent: true },
      { source: '/ההשפעת-מצב-הרוח-של-בעל-העסק-על-התפוקה', destination: '/knowledge', permanent: true },
      { source: '/האם-כוס-קפה-עם-לקוח-בבית-קפה-נחשבת-הוצאה', destination: '/knowledge', permanent: true },
      { source: '/פיצוי-לנערים-ונערות-שעבדו-במקום-עבודת', destination: '/knowledge', permanent: true },
      { source: '/ילדכם-עבר-ועדת-השמה-יתכן-ואתם-זכאים-לנק', destination: '/knowledge', permanent: true },
      { source: '/נקודות-זיכוי-לסטודנטים', destination: '/knowledge', permanent: true },
      { source: '/מה-הגישה-שלכם-לניהול-העסק', destination: '/knowledge', permanent: true },
      { source: '/בעל-עסק-יקר-האם-יש-לך-את-האיש-שלכם-שאתם', destination: '/knowledge', permanent: true },
      { source: '/כולם-צריכים-לנוח-בשבת-עכשיו-כהצעת-חוק', destination: '/knowledge', permanent: true },
      { source: '/האם-ניתן-לקזז-מעמ-בגין-רכישת-אופניים-ח', destination: '/knowledge', permanent: true },
      { source: '/האם-אתם-זכאי-להחזר-מס-בגין-תשלום-עודף-של', destination: '/knowledge', permanent: true },
      { source: '/לארגן-את-העבודה-אחרי-חופשה-ארוכה', destination: '/knowledge', permanent: true },
      { source: '/אחוז-מימון-גבוה-יותר-לרוכשי-דירה-ראשונ', destination: '/knowledge', permanent: true },
      { source: '/האם-בעל-עסק-שיש-לו-קופה-רושמת-מחויב-לשמו', destination: '/knowledge', permanent: true },
      { source: '/האם-ניתן-לקזז-מעמ-על-רכישת-נכס', destination: '/knowledge', permanent: true },
      { source: '/תביעה-בה-התובע-קיבל-פיצויים-מתפטר-בדין', destination: '/knowledge', permanent: true },
      { source: '/כיצד-מתייחסים-לאירוע-גיבוש-עובדים-מבח', destination: '/knowledge', permanent: true },
      { source: '/בעל-עסק-יקר-טס-לאילת-שים-לב-לדגש-הבא', destination: '/knowledge', permanent: true },
      { source: '/סוגיה-מעניינת-הקשורה-לימי-מחלה', destination: '/knowledge', permanent: true },
      { source: '/האנלוגיה-הנפלאה-בין-עסקים-וכדורגל', destination: '/knowledge', permanent: true },
      { source: '/מה-למדנו-מהמונדיאל-האחרון-ואיך-זה-קשור', destination: '/knowledge', permanent: true },
      { source: '/משכיר-נכס-בחול-בדוק-את-אפשרויות-המיסו', destination: '/knowledge', permanent: true },
      { source: '/האם-עוסק-מורשה-יכול-לרשום-מספר-עסקים-על', destination: '/knowledge', permanent: true },
      { source: '/היתרונות-שלך-בתור-בעל-עסק-להעביר-אלינו', destination: '/knowledge', permanent: true },
      { source: '/מכירה-דרך-חנות-אינטרנטית-האם-המוכר-צרי', destination: '/knowledge', permanent: true },
      { source: '/איך-לבדוק-בעצמך-ללא-עלות-אם-החברה-שלך-מפ', destination: '/knowledge', permanent: true },
      { source: '/למי-שפספס-מחשבון-ביטוח-לאומי-ללא-עלות', destination: '/knowledge', permanent: true },
      { source: '/יש-לך-חברה-ואתה-לא-אוהב-את-השם-אתה-לא-צרי', destination: '/knowledge', permanent: true },
      { source: '/טפסים-רלונטים-לבעלי-עסקים', destination: '/knowledge', permanent: true },
      { source: '/טיפים-למלצרים-יחשבו-כחלק-משכרם', destination: '/knowledge', permanent: true },
      { source: '/קיצור-שעות-העבודה-החל-מה-1-לאפריל', destination: '/knowledge', permanent: true },
      { source: '/ארגון-וסידור-ההתנהלות-העסקית-והחשבונ', destination: '/knowledge', permanent: true },
      { source: '/הצהרת-הון-בנישואים-חד-מיניים-בחול', destination: '/knowledge', permanent: true },
      { source: '/נדלן-לעולים-חדשים', destination: '/knowledge', permanent: true },
      { source: '/דין-הודעה-למס-הכנסה-על-סגירת-תיק', destination: '/knowledge', permanent: true },
      { source: '/דין-שימוש-במזומן', destination: '/knowledge', permanent: true },
      { source: '/נוהל-ביטול-עסקה', destination: '/knowledge', permanent: true },
      { source: '/קבלת-פטור-על-פיצויים-כתוצאה-משינוי-סטט', destination: '/knowledge', permanent: true },
      { source: '/האם-להעסיק-עובד-או-לקחת-פרילנסר-ומה-צרי', destination: '/knowledge', permanent: true },
      { source: '/איך-אני-מחליטה-אם-אני-עוסק-פטור-עוסק-מו', destination: '/knowledge', permanent: true },
      { source: '/בעל-עסק-פטור-בשורה-משמחת-עבורך', destination: '/knowledge', permanent: true },
      { source: '/מהפך-ארגוני-טכנולוגי', destination: '/knowledge', permanent: true },
      { source: '/החזר-בלו-סולר', destination: '/knowledge', permanent: true },
      { source: '/חוזרים-מקצועיים-מעמ', destination: '/knowledge', permanent: true },
      { source: '/החזר-מס', destination: '/knowledge', permanent: true },
      { source: '/מאמר-מקיף-על-כלים-טכנולוגיים-לניהול-אר', destination: '/knowledge', permanent: true },
      { source: '/מיסוי-הכנסות-מביטקוין', destination: '/knowledge', permanent: true },
      { source: '/הקלות-מיסוי-חברות-טבע-כמקרה-בוחן-נכת', destination: '/knowledge', permanent: true },
      { source: '/ביטקוין-האם-המטבע-הדיגיטלי-יחזיק-ומהר', destination: '/knowledge', permanent: true },
      { source: '/דין-חבות-מס-רכישה-לעולה-חדש', destination: '/knowledge', permanent: true },
      { source: '/תרחישים-אפשריים-במכירת-נכס-וכיצד-הם-מש', destination: '/knowledge', permanent: true },
      { source: '/מיסוי-רכישת-דירה-ראשונה', destination: '/knowledge', permanent: true },
      { source: '/תשלום-אגרה-מופחתת-לרשם-החברות-עד-תאריך-3', destination: '/knowledge', permanent: true },
      { source: '/שווי-רכב', destination: '/knowledge', permanent: true },
      { source: '/דיווח-חשבוניות-מקוון', destination: '/knowledge', permanent: true },
      { source: '/חוק-מס-הכנסה-הגדלת-נקודות-זיכוי-להורים', destination: '/knowledge', permanent: true },
      { source: '/מס-ריבוי-דירות', destination: '/knowledge', permanent: true },
      { source: '/רשות-המסים-מפרסמת-הוראת-פרשנות-חדשה', destination: '/knowledge', permanent: true },
      { source: '/רשימת-היישובים-המזכים', destination: '/knowledge', permanent: true },
      { source: '/החזר-מס-שבח', destination: '/knowledge', permanent: true },
      { source: '/הערכות-לקראת-תום-שנת-מס-2016', destination: '/knowledge', permanent: true },
      { source: '/פנסיה-לעצמאים', destination: '/knowledge', permanent: true },
      { source: '/שר-האוצר-ורשות-המסים-יביאו-לממשלה-ולוו', destination: '/knowledge', permanent: true },
      { source: '/רעידת-אדמה-בעולם-התיירות', destination: '/knowledge', permanent: true },
      { source: '/כללי-מיסוי-על-מתנות', destination: '/knowledge', permanent: true },
      { source: '/צעד-נוסף-לעבר-ניהול-ירוק', destination: '/knowledge', permanent: true },
      { source: '/דגשים-לגבי-בקשת-חופשה-מהמעסיק', destination: '/knowledge', permanent: true },
      { source: '/תיקון-לחוק-בנוגע-לדרך-חישוב-גמלאת-אימה', destination: '/knowledge', permanent: true },
      { source: '/בן-זוגך-בת-זוגך-במילואים-מגיע-לך-להעדר', destination: '/knowledge', permanent: true },
      { source: '/עצמאיים-ומשרתים-במילואים-זכאים-לתגמו', destination: '/knowledge', permanent: true },
      { source: '/מעסיק-נערים-בגילאים-16-18', destination: '/knowledge', permanent: true },
      { source: '/שינוי-בחוק-ביטוח-לאומי-דמי-לידה', destination: '/knowledge', permanent: true },
      { source: '/מיסוי-על-זכיות-בפרסים-והגרלות', destination: '/knowledge', permanent: true },
      { source: '/עצמאי-בעל-עסק-אתה-חייב-לחסוך-לפנסיה', destination: '/knowledge', permanent: true },
      { source: '/סערה-בעולם-הנדלן-חוק-מס-דירה-שלישית-יב', destination: '/knowledge', permanent: true },
      { source: '/צעד-אחד-לפני-המתחרה', destination: '/knowledge', permanent: true },
      { source: '/דגשים-חשובים-ביותר-לפני-חתימת-חוזה', destination: '/knowledge', permanent: true },
      { source: '/האם-בתור-בעל-עסק-אתה-חייב-רואה-חשבון', destination: '/knowledge', permanent: true },
      { source: '/הכוונה-בתחום-הפיננסים-והמיסוי-לגיל-הז', destination: '/knowledge', permanent: true },
      { source: '/שלב-ראשון-בבניית-תוכנית-עסקית-הגדרת-חז', destination: '/knowledge', permanent: true },
      { source: '/בניית-תוכנית-עסקית-הגדרת-מטרות-ויעדים', destination: '/knowledge', permanent: true },
      { source: '/מחלק-דיבידנד-עד-ה-30-09-17-יתכן-מאוד-ותוכל-להנ', destination: '/knowledge', permanent: true },
      { source: '/בעל-עסק-כיצד-תיצור-בידול-על-פני-המתחרים', destination: '/knowledge', permanent: true },
      { source: '/התמודדות-עם-משברים-בעסק', destination: '/knowledge', permanent: true },
      { source: '/גמלאים-יקרים-ריכזנו-עבורכם-הטבות-מס-אש', destination: '/knowledge', permanent: true },
      { source: '/טיפים-פרקטיים-שיעזרו-להתמודד-עם-מועדי', destination: '/knowledge', permanent: true },
      { source: '/חדשות-טובות-למשקיעים-בחול-הפוסט-מיו', destination: '/knowledge', permanent: true },
      { source: '/הוצאות-מוכרות', destination: '/knowledge', permanent: true },
      { source: '/פנסייה-לעצמאיים', destination: '/knowledge', permanent: true },
      { source: '/בעל-עסק-יקר-משכיר-נכס-המאמר-הבא-הוא-בשב', destination: '/knowledge', permanent: true },
      { source: '/אחת-ההחלטות-הכי-חשובות-שנעשה-בעסק', destination: '/knowledge', permanent: true },
      { source: '/הגבלה-למחזור-עסקאות-לעוסק-פטור-לשנת-2017', destination: '/knowledge', permanent: true },
      { source: '/רעיון-נוסף-מעבר-לפינה-להפחית-את-נטל-המס', destination: '/knowledge', permanent: true },
      { source: '/בעל-עסק-יקר-פתחנו-עבורך-קבוצת-פייסבוק-ב', destination: '/knowledge', permanent: true },
      { source: '/הוצאות-מוכרות-בעבודה-מהבית', destination: '/knowledge', permanent: true },
      { source: '/תיאום-מס-לא-מסובך-כמו-שזה-נשמע', destination: '/knowledge', permanent: true },
      { source: '/בעלי-דירות-יקרים-מכירים-את-סוגי-מיסוי-ע', destination: '/knowledge', permanent: true },
      { source: '/קבלת-טיפ-מלקוח-ולא-ידעת-בדיוק-איך-הרשוי', destination: '/knowledge', permanent: true },
      { source: '/הקלה-משמעותית-במסים-להורים-לילדים-בעל', destination: '/knowledge', permanent: true },
      { source: '/לקראת-סוף-השנה-ריכזנו-עבורך-טיפים-לעסק', destination: '/knowledge', permanent: true },
      { source: '/קרן-השתלמות-לעצמאים', destination: '/knowledge', permanent: true },
      { source: '/טיפ-סוף-שנה-מס-2', destination: '/knowledge', permanent: true },
      { source: '/טיפ-סוף-שנה-מס-3', destination: '/knowledge', permanent: true },
      { source: '/טיפ-סוף-שנה-מס-4', destination: '/knowledge', permanent: true },
      { source: '/טיפ-סוף-שנה-מס-5', destination: '/knowledge', permanent: true },
      { source: '/טיפ-סוף-שנה-מס-6', destination: '/knowledge', permanent: true },
      { source: '/טיפ-סוף-שנה-מס-7', destination: '/knowledge', permanent: true },
      { source: '/טיפ-סוף-שנה-מס-8', destination: '/knowledge', permanent: true },
      { source: '/הערכות-עצמאים-לתום-שנת-מס-2017', destination: '/knowledge', permanent: true },
      { source: '/הערכות-חברות-לתום-שנת-2017', destination: '/knowledge', permanent: true },

      // ── Catch-all patterns for old WP URL structures ────────────────
      { source: '/category/:path*', destination: '/knowledge', permanent: true },
      { source: '/tag/:path*', destination: '/knowledge', permanent: true },
      { source: '/page/:path*', destination: '/', permanent: true },
      { source: '/wp-content/uploads/:path*', destination: '/', permanent: true },
      { source: '/:year(\\d{4})/:month(\\d{2})/:slug', destination: '/knowledge', permanent: true },
      { source: '/author/:path*', destination: '/about', permanent: true },
    ]
  },
};

export default nextConfig;
