import { NextResponse, type NextRequest } from "next/server";

/**
 * Hebrew URL redirect map.
 * Old WP Hebrew slugs → new English routes.
 * Handled in middleware because Next.js redirect sources
 * don't match percent-encoded Hebrew characters.
 */
const hebrewRedirects: Record<string, string> = {
  // ── Service page redirects (Hebrew → English) ──────────
  "/services/החזר-מס-שבח": "/services/real-estate-tax",
  "/services/ניהול-דיונים-מול-רשויות-המס": "/services/tax-representation",
  "/services/החזרי-מס": "/services/tax-refunds",
  "/services/מענקים": "/services/grants",

  // ── Structural pages ───────────────────────────────────
  "/אודות": "/about",
  "/צור-קשר": "/contact",

  // ── P1 articles: old WP Hebrew URL → new /knowledge/[slug] ──
  "/בעלי-הכנס-מעבודה-בחול": "/knowledge/income-from-work-abroad",
  "/דירת-מגורים-מזכה": "/knowledge/qualifying-residential-apartment",
  "/הוצאות-נלוות": "/knowledge/ancillary-expenses",
  "/הוצאות-נסיעות-לחול-מוכרות-למס-הכנסה": "/knowledge/deductible-travel-expenses-abroad",
  "/היערכות-חברות-לתום-שנת-מס-2016": "/knowledge/year-end-prep-companies-2016",
  "/הערכות-חברה-לתום-שנת-2018": "/knowledge/year-end-prep-companies-2019",
  "/הקשר-בין-סעיף-174-לפקודת-מס-הכנסה-להודעת-ז": "/knowledge/section-17-4-credit-note-connection",
  "/זכאות-לשיעור-מס-מופחת-אזרחים-מעל-גיל-60": "/knowledge/reduced-tax-rate-over-60",
  "/חוזר-מקצועי-שינויים-בשכר-החל-מיום-1-בי": "/knowledge/salary-changes-january-2017",
  "/חישוב-גידול-קיטון-בהון-מקורות-ושימוש": "/knowledge/wealth-increase-decrease-sources-uses",
  "/כללים-להוצאת-הודעת-זיכוי-חשבונית-זיכו": "/knowledge/credit-note-rules",
  "/מענק-עבודה": "/knowledge/work-grant-negative-income-tax",
  "/סוגי-תשלומים-שהעברתם-לתושב-חוץ-פטורה-מ": "/knowledge/payments-to-foreign-residents-withholding-exempt",
  "/פטור-חד-פעמי-ממס-שבח-על-2-דירות": "/knowledge/one-time-betterment-tax-exemption-two-apartments",
  "/פטור-ממס-שבח": "/knowledge/betterment-tax-exemption",
  "/פטור-ממשיכת-כספי-תגמולים-החייבים-ב-35-מס": "/knowledge/severance-fund-withdrawal-35-percent-exemption",
  "/פריסת-מס-שבח": "/knowledge/betterment-tax-spreading",
  "/ריכוז-טבלת-שיעורי-המס-החלים-על-הכנסות-ו": "/knowledge/tax-rate-table-summary",
  "/שאלות-ותשובות-בנושא-דברים-שחובה-בחשבו": "/knowledge/invoice-requirements-faq",
  "/תיקון-190": "/knowledge/amendment-190",
  "/תשלום-מס-שבח": "/knowledge/betterment-tax-payment",

  // ── P2 bumped articles ─────────────────────────────────
  "/הקפאת-עדכוני-מס-ומס-יסף": "/knowledge/tax-bracket-freeze-surcharge-2025",
  "/חברת-מעטים": "/knowledge/closely-held-company",
  "/עדכון-חקיקה-מעמ-18": "/knowledge/vat-18-percent-update-2025",
  "/רווחים-כלואים": "/knowledge/trapped-profits",

  // ── Batch 2 articles ───────────────────────────────────
  "/מעמ-בגין-שכט-לשירותי-ייעוץ-לחברה-בחול": "/knowledge/vat-consulting-fees-foreign-company",
  "/האם-יש-לגבות-17-מעמ-לחברה-מחוץ-לאילת-בגין": "/knowledge/vat-eilat-interest-loan",
  "/מעמ-0-לנותני-שירותים-לאילת": "/knowledge/vat-zero-rate-tourist-services",
  "/מעמ-על-תווי-שי": "/knowledge/vat-on-gift-vouchers",
  "/תשלום-מעמ-עבור-שטח-בדירה-המשמש-לעסק": "/knowledge/vat-home-office-space",
  "/הגבלות-חדשות-בתחום-הנדלן-החל-מה-1-לינוא": "/knowledge/real-estate-restrictions-2019",
  "/האם-בעל-עסק-חייב-להפריש-לקופת-פנסיה-או-י": "/knowledge/employer-pension-vs-provident-fund",
  "/חוק-דמי-מחלה-לעובד": "/knowledge/employee-sick-pay-law",
  "/פיצויים-לעובד-שהתפטר-עקב-העתקת-מקום-מג": "/knowledge/resignation-relocation-severance",
  "/זכאות-לפיצויים-ודמי-אבטלה-לעובדת-שילד": "/knowledge/maternity-severance-unemployment",
  "/האם-בעל-עסק-שמעברים-לו-תשלום-בהעברה-בנק": "/knowledge/bank-transfer-receipt-requirement",
  "/שפת-חשבונית-לבעל-עסק-הנותן-שירות-מוכר-מ": "/knowledge/invoice-language-foreign-clients",
  "/עסק-חדש-ברכותינו-דגשים-חשובים-להתחלה": "/knowledge/opening-new-business",
  "/הפחתה-ביטוח-לאומי-לעצמאים": "/knowledge/national-insurance-self-employed",
  "/האם-ניתן-לדרוש-את-יתרת-ההשקעה-על-נכס-כהו": "/knowledge/remaining-asset-investment-current-expense",
  "/הוראות-ניהול-ספרים-מס-הכנסה": "/knowledge/bookkeeping-requirements-income-tax",
  "/הורחב-מתווה-הפיצויים-לתושבי-הדרום": "/knowledge/southern-residents-compensation-expansion",
  "/עדכון-לבעלי-עסקים-באיזור-עוטף-עזה-והדר": "/knowledge/gaza-envelope-business-update",
  "/הפרשה-חשבונאית": "/knowledge/accounting-provision-tax-recognition",

  // ── P1/P2 articles not republished → knowledge hub ─────
  "/בלוק-בדף-הבית": "/knowledge",
  "/איחוד-עוסקים-דוחות-ודיווחים-לרשויות": "/knowledge",
  "/היערכות-עוסקים-פטורים-לתום-שנת-המס-2016": "/knowledge",
  "/זיכוי-בגין-ילדים-קטנים": "/knowledge",
  "/זיכוי-בגין-סיום-תואר-אקדמי": "/knowledge",
  "/זיכוי-בעד-ילדים-נטולי-יכולת": "/knowledge",
  "/זיכוי-הורה-גרוש-מזונות-2": "/knowledge",
  "/זיכוי-הנצחת-בן-משפחה-חיל-שוטר-פעולות-אי": "/knowledge",
  "/זיכוי-ליחיד-במשפחה-חד-הורית": "/knowledge",
  "/זיכוי-לתושבים-ביישובים-מזכים": "/knowledge",
  "/זיכוי-ממס-הכנסה-לעולה-חדש": "/knowledge",
  "/זיכוי-מס-בגין-תרומה": "/knowledge",
  "/מדרגות-מס-2006-2017": "/knowledge",
  "/מספר-עובדות-מדרגות-מס": "/knowledge",
  "/סעיף-45א-נקודות-זיכוי-בגין-ילד-נטול-יכול": "/knowledge",
  "/ריבית-סעיף-3ט-לפקודה": "/knowledge",

  // ── P3 articles → knowledge hub ────────────────────────
  "/אאא": "/knowledge",
  "/אופן-העברת-מידע-למנהל-מס-ערך-מוסף-האיזו": "/knowledge",
  "/אופן-חישוב-שכירות-הכנסה-מדירת-מגורים": "/knowledge",
  "/בדיקת-זכאות-לסטודנטים": "/knowledge",
  "/במסגרת-חוק-צמצום-שימוש-מזומן-דין-עסקאו": "/knowledge",
  "/גיוס-מנהלת-חשבונות": "/knowledge",
  "/דרישת-הצהרת-הון-מתושב-חוץ": "/knowledge",
  "/האם-פיצוי-בגין-הפרת-הסכם-מחוייב-במעמ": "/knowledge",
  "/הגבלות-מקרקעין-2019": "/knowledge",
  "/הודעה-על-דחיית-מועד-הגשת-דיווח-בגין-עמ": "/knowledge",
  "/היבטים-פליליים-בהגשת-הצהרת-הון": "/knowledge",
  "/הסבר-על-מסלול-מקוצר-להוצאה-לפועל-בהתאם": "/knowledge",
  "/הערכות-הגשה-דוחות-שנת-2017": "/knowledge",
  "/הערכות-הגשת-דוחות": "/knowledge",
  "/הפחתת-מס-חברות": "/knowledge",
  "/הפרשה-חשבונאית-באילו-מצבים-ניתן-להכיר": "/knowledge",
  "/תיקון-חוק-הטבות-וייעוץ-מס": "/knowledge",
  "/חוק-חופשה-תוספת-לחוק-יום-בחירה-עובד": "/knowledge",
  "/טיפים-למלצרים-יחוייבו-במעמ": "/knowledge",
  "/כמה-נקודות-שחשוב-להכיר-לגבי-העסקת-נערי": "/knowledge",
  "/מבחנים-להכרה-בחוב-אבוד": "/knowledge",
  "/מחזיקים-בחוב-אבוד-עקב-אי-תשלום-רעיון-נו": "/knowledge",
  "/מעמ-על-רכב-להסעת-נוסעים": "/knowledge",
  "/מקרים-בהם-יש-לדווח-למעמ-דיווח-מפורט": "/knowledge",
  "/ניהול-תזרים-מזומנים": "/knowledge",
  "/נכסים-והתחייבויות-בהצהרת-הון": "/knowledge",
  "/רווחים-כלואים-וחברת-מעטים": "/knowledge",
  "/עקרון-התא-המשפחתי": "/knowledge",
  "/פחת-על-אתר-אינטרנט": "/knowledge",
  "/פינת-ההשראה-אין-גיל-צעיר-מדי-להגשים-חלו": "/knowledge",
  "/פריסת-מס-פיצויים-חייבים-במס": "/knowledge",
  "/קיבוע-זכויות-פנסיה": "/knowledge",
  "/קיזוז-הפסדים-מס-שבח-2": "/knowledge",
  "/קצבת-נכות-פטורה-ממס": "/knowledge",
  "/רעידת-אדמה-בעולם-התיירות-2": "/knowledge",
  "/שימוש-מס-ופטור-לחברה-זרה-שמחזיקה-בחברה": "/knowledge",
  "/שיעור-מס-על-דיבידנד-עפי-סעיף-125ב-לפקודת-מ": "/knowledge",
  "/תיאום-מס-לא-מסובך-כמו-שזה-נשמע-2": "/knowledge",
  "/תשלום-אגרה-מופחתת-לרשם-החברות-עד-תאריך-2": "/knowledge",
  "/תשלום-מס-במקרה-של-דירת-ירושה-אותה-מחזיק": "/knowledge",

  // ── Skip articles → knowledge hub ─────────────────────
  "/בקשה-לדחיית-נקודת-זיכוי-שנדחתה-בגין-יל": "/knowledge",
  "/חישוב-הכנסה-משכירות-תושב-חוץ": "/knowledge",
  "/תושב-ישראל-בעל-חברה-ישראלית-מחזיק-בחבר": "/knowledge",

  // ── Remaining WP Hebrew posts → knowledge hub ─────────
  "/פטור-ממס-הכנסה-לאנשים-בעלי-מוגבלויות": "/knowledge",
  "/משתמש-ברכב-חברה-לצרכיך-האישיים-האם-נית": "/knowledge",
  "/עובדים-מול-ספקים-ויש-הפרשים-בחשבונית-ה": "/knowledge",
  "/האם-עדיין-צריך-לשלם-מס-על-עסקה-שבוטלה-לא": "/knowledge",
  "/משיכה-מוקדמת-מרכיב-תגמולים-בקופת-גמל-ב": "/knowledge",
  "/זכיתם-בפרס-או-הגרלה-מזל-טוב-כמה-מס-תצטר": "/knowledge",
  "/בעל-עסק-אוהב-סיכונים": "/knowledge",
  "/קבלו-כמה-טיפים-לחיסכון-במס": "/knowledge",
  "/עובדי-הייטק-המחזיקים-אופציות-שימו-לב-ל": "/knowledge",
  "/פינת-ההשראה-לעולם-לא-מאוחר-מדי": "/knowledge",
  "/דחיית-מועד-הגשת-הדוחות-השנתיים": "/knowledge",
  "/פטור-מתשלום-מסים-על-מוצרים-מהדיוטי-פרי": "/knowledge",
  "/דירוג-אשראי-אישי": "/knowledge",
  "/הקניון-הראשון-מחות-לאילת-ללא-מעמ": "/knowledge",
  "/דיווח-נכסים-והתחייבויות-לבן-זוג-בנישו": "/knowledge",
  "/החזר-מעמ-על-רכב-שמשמש-להסעת-נוסעים-בלב": "/knowledge",
  "/דין-עדכון-למס-הכנסה-בדבר-סגירת-העסק": "/knowledge",
  "/האם-העמותה-שאתם-מעוניינים-לתרום-לה-מוכ": "/knowledge",
  "/הטבות-מס-לנשים": "/knowledge",
  "/בדקו-מה-הסכום-המירבי-המותר-לשימוש-לתשל": "/knowledge",
  "/סימולטור-שימושי-בהמשך-לחוק-צמצום-השימ": "/knowledge",
  "/מיסים-על-מטבעות-וירטואליים": "/knowledge",
  "/תזכורת-להורים-עובדיםתיקון-לחוק-מס-הכנ": "/knowledge",
  "/תזכורת-מרשות-המסים-למשתחררים-משירות-צ": "/knowledge",
  "/לבעלי-עסקים-באיזור-עוטף-עזה": "/knowledge",
  "/תכנון-ופיתוח-העסק": "/knowledge",
  "/הוצאות-מוכרות-לרכב-המיועד-להסעת-תיירי": "/knowledge",
  "/כיצד-יש-לפעול-בעת-השמדת-מלאי-לפי-הוראות": "/knowledge",
  "/הערכות-חברות-לתום-שנת-2018": "/knowledge",
  "/תקרת-עוסק-פטור-2018": "/knowledge",
  "/הערכות-עצמאים-לתום-שנת-מס-2018": "/knowledge",
  "/המערכת-שעשויה-להוזיל-לנו-את-הריביות-על": "/knowledge",
  "/האם-סיוע-כלכלי-מחוייב-במעמ": "/knowledge",
  "/האם-מכירת-ציוד-לעסק-נכנס-כחלק-מתקרת-עוס": "/knowledge",
  "/האם-אפשר-להוציא-חשבוניות-קבלות-במסמך-word": "/knowledge",
  "/האם-כוס-קפה-עם-לקוח-בבית-קפה-נחשבת-הוצא-2": "/knowledge",
  "/מה-אחוז-ניכוי-מעמ-על-רכישת-סמארטפון": "/knowledge",
  "/משיכת-כספים-מקופת-פנסיה-ללא-אישור-מעסי": "/knowledge",
  "/ההשפעת-מצב-הרוח-של-בעל-העסק-על-התפוקה": "/knowledge",
  "/האם-כוס-קפה-עם-לקוח-בבית-קפה-נחשבת-הוצאה": "/knowledge",
  "/פיצוי-לנערים-ונערות-שעבדו-במקום-עבודת": "/knowledge",
  "/ילדכם-עבר-ועדת-השמה-יתכן-ואתם-זכאים-לנק": "/knowledge",
  "/נקודות-זיכוי-לסטודנטים": "/knowledge",
  "/מה-הגישה-שלכם-לניהול-העסק": "/knowledge",
  "/בעל-עסק-יקר-האם-יש-לך-את-האיש-שלכם-שאתם": "/knowledge",
  "/כולם-צריכים-לנוח-בשבת-עכשיו-כהצעת-חוק": "/knowledge",
  "/האם-ניתן-לקזז-מעמ-בגין-רכישת-אופניים-ח": "/knowledge",
  "/האם-אתם-זכאי-להחזר-מס-בגין-תשלום-עודף-של": "/knowledge",
  "/לארגן-את-העבודה-אחרי-חופשה-ארוכה": "/knowledge",
  "/אחוז-מימון-גבוה-יותר-לרוכשי-דירה-ראשונ": "/knowledge",
  "/האם-בעל-עסק-שיש-לו-קופה-רושמת-מחויב-לשמו": "/knowledge",
  "/האם-ניתן-לקזז-מעמ-על-רכישת-נכס": "/knowledge",
  "/תביעה-בה-התובע-קיבל-פיצויים-מתפטר-בדין": "/knowledge",
  "/כיצד-מתייחסים-לאירוע-גיבוש-עובדים-מבח": "/knowledge",
  "/בעל-עסק-יקר-טס-לאילת-שים-לב-לדגש-הבא": "/knowledge",
  "/סוגיה-מעניינת-הקשורה-לימי-מחלה": "/knowledge",
  "/האנלוגיה-הנפלאה-בין-עסקים-וכדורגל": "/knowledge",
  "/מה-למדנו-מהמונדיאל-האחרון-ואיך-זה-קשור": "/knowledge",
  "/משכיר-נכס-בחול-בדוק-את-אפשרויות-המיסו": "/knowledge",
  "/האם-עוסק-מורשה-יכול-לרשום-מספר-עסקים-על": "/knowledge",
  "/היתרונות-שלך-בתור-בעל-עסק-להעביר-אלינו": "/knowledge",
  "/מכירה-דרך-חנות-אינטרנטית-האם-המוכר-צרי": "/knowledge",
  "/איך-לבדוק-בעצמך-ללא-עלות-אם-החברה-שלך-מפ": "/knowledge",
  "/למי-שפספס-מחשבון-ביטוח-לאומי-ללא-עלות": "/knowledge",
  "/יש-לך-חברה-ואתה-לא-אוהב-את-השם-אתה-לא-צרי": "/knowledge",
  "/טפסים-רלונטים-לבעלי-עסקים": "/knowledge",
  "/טיפים-למלצרים-יחשבו-כחלק-משכרם": "/knowledge",
  "/קיצור-שעות-העבודה-החל-מה-1-לאפריל": "/knowledge",
  "/ארגון-וסידור-ההתנהלות-העסקית-והחשבונ": "/knowledge",
  "/הצהרת-הון-בנישואים-חד-מיניים-בחול": "/knowledge",
  "/נדלן-לעולים-חדשים": "/knowledge",
  "/דין-הודעה-למס-הכנסה-על-סגירת-תיק": "/knowledge",
  "/דין-שימוש-במזומן": "/knowledge",
  "/נוהל-ביטול-עסקה": "/knowledge",
  "/קבלת-פטור-על-פיצויים-כתוצאה-משינוי-סטט": "/knowledge",
  "/האם-להעסיק-עובד-או-לקחת-פרילנסר-ומה-צרי": "/knowledge",
  "/איך-אני-מחליטה-אם-אני-עוסק-פטור-עוסק-מו": "/knowledge",
  "/בעל-עסק-פטור-בשורה-משמחת-עבורך": "/knowledge",
  "/מהפך-ארגוני-טכנולוגי": "/knowledge",
  "/החזר-בלו-סולר": "/knowledge",
  "/חוזרים-מקצועיים-מעמ": "/knowledge",
  "/החזר-מס": "/knowledge",
  "/מאמר-מקיף-על-כלים-טכנולוגיים-לניהול-אר": "/knowledge",
  "/מיסוי-הכנסות-מביטקוין": "/knowledge",
  "/הקלות-מיסוי-חברות-טבע-כמקרה-בוחן-נכת": "/knowledge",
  "/ביטקוין-האם-המטבע-הדיגיטלי-יחזיק-ומהר": "/knowledge",
  "/דין-חבות-מס-רכישה-לעולה-חדש": "/knowledge",
  "/תרחישים-אפשריים-במכירת-נכס-וכיצד-הם-מש": "/knowledge",
  "/מיסוי-רכישת-דירה-ראשונה": "/knowledge",
  "/תשלום-אגרה-מופחתת-לרשם-החברות-עד-תאריך-3": "/knowledge",
  "/שווי-רכב": "/knowledge",
  "/דיווח-חשבוניות-מקוון": "/knowledge",
  "/חוק-מס-הכנסה-הגדלת-נקודות-זיכוי-להורים": "/knowledge",
  "/מס-ריבוי-דירות": "/knowledge",
  "/רשות-המסים-מפרסמת-הוראת-פרשנות-חדשה": "/knowledge",
  "/רשימת-היישובים-המזכים": "/knowledge",
  "/החזר-מס-שבח": "/knowledge",
  "/הערכות-לקראת-תום-שנת-מס-2016": "/knowledge",
  "/פנסיה-לעצמאים": "/knowledge",
  "/שר-האוצר-ורשות-המסים-יביאו-לממשלה-ולוו": "/knowledge",
  "/רעידת-אדמה-בעולם-התיירות": "/knowledge",
  "/כללי-מיסוי-על-מתנות": "/knowledge",
  "/צעד-נוסף-לעבר-ניהול-ירוק": "/knowledge",
  "/דגשים-לגבי-בקשת-חופשה-מהמעסיק": "/knowledge",
  "/תיקון-לחוק-בנוגע-לדרך-חישוב-גמלאת-אימה": "/knowledge",
  "/בן-זוגך-בת-זוגך-במילואים-מגיע-לך-להעדר": "/knowledge",
  "/עצמאיים-ומשרתים-במילואים-זכאים-לתגמו": "/knowledge",
  "/מעסיק-נערים-בגילאים-16-18": "/knowledge",
  "/שינוי-בחוק-ביטוח-לאומי-דמי-לידה": "/knowledge",
  "/מיסוי-על-זכיות-בפרסים-והגרלות": "/knowledge",
  "/עצמאי-בעל-עסק-אתה-חייב-לחסוך-לפנסיה": "/knowledge",
  "/סערה-בעולם-הנדלן-חוק-מס-דירה-שלישית-יב": "/knowledge",
  "/צעד-אחד-לפני-המתחרה": "/knowledge",
  "/דגשים-חשובים-ביותר-לפני-חתימת-חוזה": "/knowledge",
  "/האם-בתור-בעל-עסק-אתה-חייב-רואה-חשבון": "/knowledge",
  "/הכוונה-בתחום-הפיננסים-והמיסוי-לגיל-הז": "/knowledge",
  "/שלב-ראשון-בבניית-תוכנית-עסקית-הגדרת-חז": "/knowledge",
  "/בניית-תוכנית-עסקית-הגדרת-מטרות-ויעדים": "/knowledge",
  "/מחלק-דיבידנד-עד-ה-30-09-17-יתכן-מאוד-ותוכל-להנ": "/knowledge",
  "/בעל-עסק-כיצד-תיצור-בידול-על-פני-המתחרים": "/knowledge",
  "/התמודדות-עם-משברים-בעסק": "/knowledge",
  "/גמלאים-יקרים-ריכזנו-עבורכם-הטבות-מס-אש": "/knowledge",
  "/טיפים-פרקטיים-שיעזרו-להתמודד-עם-מועדי": "/knowledge",
  "/חדשות-טובות-למשקיעים-בחול-הפוסט-מיו": "/knowledge",
  "/הוצאות-מוכרות": "/knowledge",
  "/פנסייה-לעצמאיים": "/knowledge",
  "/בעל-עסק-יקר-משכיר-נכס-המאמר-הבא-הוא-בשב": "/knowledge",
  "/אחת-ההחלטות-הכי-חשובות-שנעשה-בעסק": "/knowledge",
  "/הגבלה-למחזור-עסקאות-לעוסק-פטור-לשנת-2017": "/knowledge",
  "/רעיון-נוסף-מעבר-לפינה-להפחית-את-נטל-המס": "/knowledge",
  "/בעל-עסק-יקר-פתחנו-עבורך-קבוצת-פייסבוק-ב": "/knowledge",
  "/הוצאות-מוכרות-בעבודה-מהבית": "/knowledge",
  "/תיאום-מס-לא-מסובך-כמו-שזה-נשמע": "/knowledge",
  "/בעלי-דירות-יקרים-מכירים-את-סוגי-מיסוי-ע": "/knowledge",
  "/קבלת-טיפ-מלקוח-ולא-ידעת-בדיוק-איך-הרשוי": "/knowledge",
  "/הקלה-משמעותית-במסים-להורים-לילדים-בעל": "/knowledge",
  "/לקראת-סוף-השנה-ריכזנו-עבורך-טיפים-לעסק": "/knowledge",
  "/קרן-השתלמות-לעצמאים": "/knowledge",
  "/טיפ-סוף-שנה-מס-2": "/knowledge",
  "/טיפ-סוף-שנה-מס-3": "/knowledge",
  "/טיפ-סוף-שנה-מס-4": "/knowledge",
  "/טיפ-סוף-שנה-מס-5": "/knowledge",
  "/טיפ-סוף-שנה-מס-6": "/knowledge",
  "/טיפ-סוף-שנה-מס-7": "/knowledge",
  "/טיפ-סוף-שנה-מס-8": "/knowledge",
  "/הערכות-עצמאים-לתום-שנת-מס-2017": "/knowledge",
  "/הערכות-חברות-לתום-שנת-2017": "/knowledge",
};

export function middleware(request: NextRequest) {
  // Decode the pathname to match Hebrew characters
  let decodedPath: string;
  try {
    decodedPath = decodeURIComponent(request.nextUrl.pathname);
  } catch {
    return NextResponse.next();
  }

  const destination = hebrewRedirects[decodedPath];
  if (destination) {
    const url = request.nextUrl.clone();
    url.pathname = destination;
    url.search = "";
    return NextResponse.redirect(url, 301);
  }

  return NextResponse.next();
}

export const config = {
  // Only run middleware on paths that could be old WP slugs.
  // Skip _next, api, studio, static files.
  matcher: [
    "/((?!_next|api|studio|favicon\\.ico|.*\\.(?:png|jpg|jpeg|gif|svg|ico|css|js|woff2?|webp|xml|txt)).*)",
  ],
};
